# Name
REPO_NAME           ?= New Bilgall Train Set

# File name of *.grf, *.tar and so on
BASE_FILENAME       ?= NewBTS

# Versin
VERSION             ?= beta1.8.0
RECENT_UPDATED      ?= $(shell date +"%Y.%m.%d")
REPO_BRANCH_VERSION ?= 0

# Author's information
AUTHOR_WEBSITE      ?= https://cafe.naver.com/5pcraft
AUTHOR_EMAIL        ?= lrynizz@khu.ac.kr

# If needed, declare the minimum NML requirements
REQUIRED_NML_BRANCH  = 0.4
# MIN_NML_REVISION   = 0
